### ISSUE TITLE
 mhcflurry-downloads fetch analysis_predictor_info

### ISSUE THREAD

**Issue by plsysu** [openvax/mhcflurry#176]
**can not  download this file.**

Downloading [part 1/1]: https://github.com/openvax/mhcflurry/releases/download/pre-2.0/analysis_predictor_info.20200711.tar.bz2

0.00B [00:00, ?B/s]Traceback (most recent call last):

  File "/datapool/data0/software/miniconda3/bin/mhcflurry-downloads", line 8, in <module>
    sys.exit(run())
  File "/datapool/data0/software/miniconda3/lib/python3.7/site-packages/mhcflurry/downloads_command.py", line 123, in run
    command_functions[args.subparser_name](args)
  File "/datapool/data0/software/miniconda3/lib/python3.7/site-packages/mhcflurry/downloads_command.py", line 239, in fetch_subcommand
    unit='B', unit_scale=True, miniters=1).update_to)
  File "/datapool/data0/software/miniconda3/lib/python3.7/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/datapool/data0/software/miniconda3/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/datapool/data0/software/miniconda3/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/datapool/data0/software/miniconda3/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/datapool/data0/software/miniconda3/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/datapool/data0/software/miniconda3/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/datapool/data0/software/miniconda3/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
0.00B [00:00, ?B/s]

**Comment by timodonnell** [comment]
This should be fixed now, please give it a try again.
