### ISSUE TITLE
mhcflurry-downloads fetch random_peptide_predictions  --already-downloaded-dir 

### ISSUE THREAD

**Issue by paulsonzhang** [openvax/mhcflurry#213]
I have downloaded random_peptide_predictions  dataset from http://github.com/openvax/mhcflurry/releases/download/pan-dev1/random_peptide_predictions.20190506.tar.bz2. And use the command "mhcflurry-downloads fetch random_peptide_predictions  --already-downloaded-dir ", but get error report "OSError: Invalid data stream".

**Comment by paulsonzhang** [comment]
Copying to: /tmp/tmpqba0op1l.tar.bz2
Traceback (most recent call last):
  File "/home/biotech/anaconda_20200723/bin/mhcflurry-downloads", line 8, in <module>
    sys.exit(run())
  File "/home/biotech/anaconda_20200723/lib/python3.8/site-packages/mhcflurry/downloads_command.py", line 123, in run
    command_functions[args.subparser_name](args)
  File "/home/biotech/anaconda_20200723/lib/python3.8/site-packages/mhcflurry/downloads_command.py", line 251, in fetch_subcommand
    names = tar.getnames()
  File "/home/biotech/anaconda_20200723/lib/python3.8/tarfile.py", line 1795, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]
  File "/home/biotech/anaconda_20200723/lib/python3.8/tarfile.py", line 1787, in getmembers
    self._load()        # all members, we first have to
  File "/home/biotech/anaconda_20200723/lib/python3.8/tarfile.py", line 2372, in _load
    tarinfo = self.next()
  File "/home/biotech/anaconda_20200723/lib/python3.8/tarfile.py", line 2303, in next
    self.fileobj.seek(self.offset - 1)
  File "/home/biotech/anaconda_20200723/lib/python3.8/bz2.py", line 278, in seek
    return self._buffer.seek(offset, whence)
  File "/home/biotech/anaconda_20200723/lib/python3.8/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/home/biotech/anaconda_20200723/lib/python3.8/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream

**Comment by timodonnell** [comment]
Hmm I'm not sure. Are you able to uncompress the file manually using bzip2?

**Comment by paulsonzhang** [comment]
Thanks! I have fetched the file successfully now! It seems that the download file before is incomplete.
