### ISSUE TITLE
mhcflurry-predict INPUT.csv –out RESULT.csv

### ISSUE THREAD

**Issue by lzy604** [openvax/mhcflurry#229]
Dear team,

Thanks for develop this useful tool. I want to run the command line. But I provide the input.csv containing columns “allele”, “peptide”. But it is not working. Could you help for the format of this file? 

I attach the input.csv and copy the error here. Thanks

[HLA1_allele_peptide.csv](https://github.com/openvax/mhcflurry/files/13300685/HLA1_allele_peptide.csv)
Traceback (most recent call last):
  File "/Users/liz36/anaconda3/lib/python3.11/site-packages/keras/engine/base_layer.py", line 3149, in __setattr__
    super(tf.__internal__.tracking.AutoTrackable, self).__setattr__(
AttributeError: property 'name' of 'Dense' object has no setter

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/liz36/anaconda3/bin/mhcflurry-predict", line 10, in <module>
    sys.exit(run())
             ^^^^^
  File "/Users/liz36/anaconda3/lib/python3.11/site-packages/mhcflurry/predict_command.py", line 204, in run
    predictor = Class1PresentationPredictor.load(models_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liz36/anaconda3/lib/python3.11/site-packages/mhcflurry/class1_presentation_predictor.py", line 860, in load
    affinity_predictor = Class1AffinityPredictor.load(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/liz36/anaconda3/lib/python3.11/site-packages/mhcflurry/class1_affinity_predictor.py", line 530, in load
    optimized = result.optimize()
                ^^^^^^^^^^^^^^^^^
  File "/Users/liz36/anaconda3/lib/python3.11/site-packages/mhcflurry/class1_affinity_predictor.py", line 555, in optimize
    Class1NeuralNetwork.merge(
  File "/Users/liz36/anaconda3/lib/python3.11/site-packages/mhcflurry/class1_neural_network.py", line 1176, in merge
    layer.name += "_%d" % i
    ^^^^^^^^^^
  File "/Users/liz36/anaconda3/lib/python3.11/site-packages/keras/engine/base_layer.py", line 3153, in __setattr__
    raise AttributeError(
AttributeError: Can't set the attribute "name", likely because it conflicts with an existing read-only @property of the object. Please choose a different name.

**Comment by timodonnell** [comment]
Hmm does seem like a bug. Could you give the output of running `pip freeze` ? I'm curious what version of tensorflow are you using.
